[package]
name = "ads7828"
version = "0.1.0"
edition = "2021"
description = "Device driver for the ADS7828 8 channel ADC. "
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
